CREATE TABLE IF NOT EXISTS users(
  id bigint PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(50) NOT NULL,
  email VARCHAR(50) NOT NULL,
  hashed_password VARCHAR(200) NOT NULL,
  contact_number VARCHAR(15) NOT NULL,
  status ENUM('ACTIVE','INACTIVE','PENDING_APPROVAL') DEFAULT 'ACTIVE',
  created_by VARCHAR(100) NOT NULL,
  updated_by VARCHAR(100) NOT NULL,
  created_at datetime DEFAULT CURRENT_TIMESTAMP,
  updated_at datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
